apiVersion: apps/v1
kind: Deployment
metadata:
  name: dice-app
  namespace: o11y
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dice-app
  template:
    metadata:
      labels:
        app: dice-app
    spec:
      containers:
      - name: dice-app
        image: dice-app:v1
        ports:
        - containerPort: 8080
          name: http
        - containerPort: 4317
          name: otlp-grpc
        - containerPort: 4318
          name: otlp-http
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "alloy-service:4317"
        - name: OTEL_EXPORTER_OTLP_HTTP_ENDPOINT
          value: "http://localhost/otlp/v1/logs"
---
apiVersion: v1
kind: Service
metadata:
  name: dice-app
  namespace: o11y
spec:
  selector:
    app: dice-app
  ports:
  - port: 8080
    targetPort: 8080
    name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dice-app-ingress
  namespace: o11y
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /rolldice
        pathType: Prefix
        backend:
          service:
            name: dice-app
            port:
              number: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alloy-ingress
  namespace: o11y
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          service:
            name: alloy-service
            port:
              number: 4318
